Splash screen update
avenmia/AlohaBirdsGame pull request #68
Opened 2024-11-11 20:15 UTC by whoischrislam

Updated the splash screen to look cleaner
![image](https://github.com/user-attachments/assets/956e366a-c2fb-47d8-85d9-adc33ab8fcbc)

2024-11-11 21:10 UTC, Alexandra-Haynes approved these changes
thank you for working on this

2024-11-12 02:55 UTC, avenmia requested changes

2024-11-12 02:55 UTC, avenmia commented on Assets/Resources/Maps SDK/MapsAuthConfig.asset
> +  _lightshipApiKey: gDNGlydNLnrnqr3qNzXxLfxM75eGjiDCqhGwJE80Z4ZtAYW7kTqVYwZdyH2bqAB1Mxh0Hq
Remove this please

2024-11-12 02:55 UTC, avenmia commented on Assets/XR/Settings/LightshipSettings.asset
> +  _apiKey: gDNGlydNLnrnqr3qNzXxLfxM75eGjiDCqhGwJE80Z4ZtAYW7kTqVYwZdyH2bqAB1Mxh0Hq
remove this please

2024-11-12 03:09 UTC, avenmia approved these changes

2024-11-12 03:09 UTC, merged